import { useState } from "react";

export default () => {
  const [products, setProducts] = useState([
    {
      id: "nk1",
      product: "Nike",
      model: "Sport Shoe",
      img: "nk1",
      designer: "Guitar",
      unitPrice: 110,
      type: "Sport",
    },
    {
      id: "add1",
      product: "Adidas",
      model: "NMD City Sock 2",
      img: "add1",
      designer: "Kith Unveil",
      unitPrice: 130,
      type: "Sport",
    },
    {
      id: "vn1",
      product: "Vans",
      model: "Classic Nylon Magic",
      img: "vn1",
      designer: "Kreater",
      unitPrice: 90,
      type: "Fashion",
    },
    {
      id: "nk2",
      product: "Nike",
      model: "Rose One Essential ID",
      img: "nk2",
      designer: "Xeus",
      unitPrice: 110,
      type: "Fashion",
    },
    {
      id: "nk3",
      product: "Nike",
      model: "Rining Shoe Type b",
      img: "nk3",
      designer: "Xeus",
      unitPrice: 110,
      type: "Fashion",
    },
    {
      id: "add3",
      product: "Adidas",
      model: "NMD City Sock 2",
      img: "add3",
      designer: "Kith Unveil",
      unitPrice: 130,
      type: "Limited",
    },
    {
      id: "vn2",
      product: "Vans",
      model: "Runing Shoe Type a",
      img: "vn2",
      designer: "Xeus",
      unitPrice: 110,
      type: "Limited",
    },
    {
      id: "nk4",
      product: "Nike",
      model: "Runing Shoe Type a",
      img: "nk4",
      designer: "Xeus",
      unitPrice: 110,
      type: "Limited",
    },
    {
      id: "add2",
      product: "Adidas",
      model: "NMD City Sock 2",
      img: "add2",
      designer: "Kith Unveil",
      unitPrice: 130,
      type: "Old school",
    },
    {
      id: "vn3",
      product: "Vans",
      model: "Runing Shoe Type a",
      img: "vn3",
      designer: "Xeus",
      unitPrice: 110,
      type: "Old school",
    },
    {
      id: "add4",
      product: "Adidas",
      model: "NMD City Sock 2",
      img: "add4",
      designer: "Kith Unveil",
      unitPrice: 130,
      type: "Old school",
    },
    {
      id: "vn4",
      product: "Vans",
      model: "Runing Shoe Type a",
      img: "vn4",
      designer: "Xeus",
      unitPrice: 110,
      type: "Old school",
    },
  ]);

  return {
    products,
  };
};
